# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - uses: actions/checkout@v2
    - name: Install Modules
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn run lint
    - name: Test
      run: yarn jest --ci --coverage && yarn coverage
    - name: Code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true 
        directory: ./coverage/
        path_to_write_report: ./coverage/codecov_report.gz

    
      
